# Generated by Django 3.1.5 on 2021-12-18 21:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=80, verbose_name='first player')),
                ('second', models.CharField(max_length=80, verbose_name='second player')),
                ('winner', models.CharField(max_length=80, null=True, verbose_name='winner')),
                ('winner_streak', models.IntegerField(null=True, verbose_name='winner streak')),
                ('fPoints', models.IntegerField(null=True, verbose_name='first points')),
                ('sPoints', models.IntegerField(null=True, verbose_name='second points')),
                ('gameId', models.CharField(max_length=16, unique=True, verbose_name='winner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueId', models.IntegerField(default=1616)),
                ('queue', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, null=True), size=None), size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(max_length=80, verbose_name='last name')),
                ('username', models.CharField(max_length=80, null=True, unique=True)),
                ('password', models.CharField(max_length=80, null=True, unique=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TCAPI.token')),
                ('win_streak', models.IntegerField(default=0, null=True, verbose_name='win streak')),
                ('best_streak', models.IntegerField(default=0, null=True, verbose_name='best streak')),
                ('wins', models.IntegerField(default=0, null=True, verbose_name='wins')),
                ('losses', models.IntegerField(default=0, null=True, verbose_name='losses')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
        ),
    ]
