# Generated by Django 3.1.5 on 2021-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cg_Id',
            field=models.CharField(max_length=16, null=True, verbose_name='current game id'),
        ),
        migrations.AddField(
            model_name='user',
            name='in_game',
            field=models.BooleanField(default=False, verbose_name='in game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameId',
            field=models.CharField(max_length=16, unique=True, verbose_name='game id'),
        ),
    ]
