# Generated by Django 3.1.5 on 2021-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0002_auto_20211220_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='email code')),
                ('inputCode', models.CharField(max_length=4, verbose_name='input email code')),
                ('email', models.CharField(max_length=80, verbose_name='email code email')),
                ('username', models.CharField(max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
