# Generated by Django 3.1.5 on 2022-01-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0004_commentorbug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
