# Generated by Django 3.1.5 on 2022-02-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0005_auto_20220114_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_create_game',
            field=models.BooleanField(default=False, verbose_name='in create game'),
        ),
        migrations.AddField(
            model_name='user',
            name='in_queue',
            field=models.BooleanField(default=False, verbose_name=' in queue'),
        ),
        migrations.AddField(
            model_name='user',
            name='logged_in',
            field=models.BooleanField(default=False, verbose_name='logged in'),
        ),
    ]
