# Generated by Django 3.1.5 on 2022-03-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0006_auto_20220211_0422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
