# Generated by Django 3.1.5 on 2022-04-21 02:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0007_delete_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=80, verbose_name='sender')),
                ('reciever', models.CharField(max_length=80, verbose_name='reciever')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted invite')),
                ('cancel', models.BooleanField(default=False, verbose_name='cancel invite')),
                ('gameId', models.CharField(max_length=16, unique=True, verbose_name='game id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80, null=True), blank=True, null=True, size=None), blank=True, default=list, null=True, size=None),
        ),
    ]
