# Generated by Django 3.1.5 on 2022-10-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0010_auto_20221011_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
