# Generated by Django 3.1.5 on 2022-10-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0011_auto_20221011_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_code',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
