# Generated by Django 3.1.5 on 2022-10-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0012_user_p_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='p_code',
            field=models.IntegerField(null=True),
        ),
    ]
