# Generated by Django 3.1.5 on 2022-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0014_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_code_time',
            field=models.DateTimeField(null=True, verbose_name='password code time added'),
        ),
    ]
