# Generated by Django 3.1.5 on 2023-11-24 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0018_auto_20221019_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_user', models.CharField(max_length=80)),
                ('receiving_user', models.CharField(max_length=80)),
                ('pending_request', models.BooleanField(default=False, verbose_name='pending request')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None), blank=True, default=list, null=True, size=None),
        ),
    ]
