# Generated by Django 3.1.5 on 2023-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0018_auto_20221019_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dev_ganache_wallet_address',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
