# Generated by Django 3.1.5 on 2023-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0019_auto_20231124_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmodel',
            name='users_names_string',
            field=models.CharField(max_length=160, null=True, unique=True, verbose_name='both users names'),
        ),
    ]
