# Generated by Django 3.1.5 on 2023-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0020_friendmodel_users_names_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestionsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersSecurityQuestionsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=160, verbose_name='question one')),
                ('answer_1', models.CharField(max_length=160, verbose_name='answer one')),
                ('question_2', models.CharField(max_length=160, verbose_name='question two')),
                ('answer_2', models.CharField(max_length=160, verbose_name='answer two')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='security_questions_answers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TCAPI.userssecurityquestionsanswers'),
        ),
    ]
