# Generated by Django 3.1.5 on 2023-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0023_user_has_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last active date'),
        ),
    ]
