# Generated by Django 3.1.5 on 2023-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0024_user_last_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='is active'),
        ),
    ]
