# Generated by Django 3.1.5 on 2023-12-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0025_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_location',
            field=models.BooleanField(default=False, verbose_name='has location'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_coordinates',
            field=models.CharField(max_length=160, null=True, verbose_name='users coordinates'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_time_zone',
            field=models.CharField(max_length=160, null=True, verbose_name='user time zone'),
        ),
    ]
