# Generated by Django 3.1.5 on 2023-12-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0026_auto_20231207_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_coordinates',
        ),
        migrations.AddField(
            model_name='user',
            name='user_latitude',
            field=models.CharField(max_length=160, null=True, verbose_name='users latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_longitude',
            field=models.CharField(max_length=160, null=True, verbose_name='users longitude'),
        ),
    ]
