# Generated by Django 3.1.5 on 2023-12-09 15:45

import TCAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0027_auto_20231207_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_title', models.CharField(max_length=80, verbose_name='league title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='league',
            field=models.IntegerField(choices=[(TCAPI.models.LeagueEnum['NOOB_TAPPER'], 1), (TCAPI.models.LeagueEnum['BAD_TAPPER'], 2), (TCAPI.models.LeagueEnum['OKAY_TAPPER'], 3), (TCAPI.models.LeagueEnum['BETTER_TAPPER'], 4), (TCAPI.models.LeagueEnum['GOOD_TAPPER'], 5), (TCAPI.models.LeagueEnum['SOLID_TAPPER'], 6), (TCAPI.models.LeagueEnum['SUPER_TAPPER'], 7), (TCAPI.models.LeagueEnum['MEGA_TAPPER'], 8), (TCAPI.models.LeagueEnum['GODLY_TAPPER'], 9)], default=1, null=True, verbose_name='league placement'),
        ),
    ]
