# Generated by Django 4.2.9 on 2024-01-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0031_user_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_task_value',
            field=models.BooleanField(default=False, null=True, verbose_name='is active task value'),
        ),
    ]
