# Generated by Django 4.2.9 on 2024-03-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0032_user_is_active_task_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_streak',
            field=models.BooleanField(default=False, verbose_name='has streak'),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_queue',
            field=models.BooleanField(default=False, verbose_name='in queue'),
        ),
    ]
