# Generated by Django 4.2.9 on 2024-03-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCAPI', '0033_user_has_streak_alter_user_in_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lost_streak',
            field=models.BooleanField(default=False, verbose_name='lost streak'),
        ),
    ]
